### PR TITLE
Add Support of net standard 2.0

### PR DESCRIPTION
**Pull request by jgiacomini**
Hello, 
I have added support of netstandard 2.0. :)
 (#38.)

### CODE REVIEW

**Comment by bytefish** [comment]
@jgiacomini Just a question, why is the netstandard2.0 target neccessary? There is a netstandard 1.3 target, that should fit. 🤔 I always thought one has to target the lower netstandard, but probably I am mistaken. 😇

**Comment by jgiacomini** [comment]
Hello @bytefish, 

It's good to have the lowest compatibility possible. 
But when you are in compatibility mode netstandard 1.3 you drag lot of depencies. (14 depencies).
=> If you provide the netstandard 2.0 you have a nuget package without any dependencies.  (+ they will use the lastest version of dll you reimport manually).

Hope that helps.

**Comment by bytefish** [comment]
@jgiacomini Thanks for the explanation! 😎 With .NET you never stop learning. 🤗 I will create a new NuGet package tommorow, which includes the updated dependency. Thanks again.

**Comment by jgiacomini** [comment]
I had the same issue in my lib :)

Maybe you can check if netstandard 1.6 is dependency less.
I didn't check hahah. 

Thanks again for your work on this lib.

**Comment by bytefish** [comment]
@jgiacomini Honestly I wonder if this isn't a NuGet bug pulling the wrong dependencies. If I target netframework 1.3, then to me it states "I support all netstandard >= 1.3". Why does it pull old dependencies. Yes, I can say it also targets 2.0 and make it easier for NuGet. But why does it needs such a hint? 🤨🤔

**Comment by jgiacomini** [comment]
Another remark. 
Do you know you can enable easily the sourcelinking with this lib => 
Microsoft.SourceLink.GitHub

An explanation here : 
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

**Comment by bytefish** [comment]
Cool! I will have a look.

**Comment by jgiacomini** [comment]
@bytefish  in your csproj you tell to nuget to user specific version of dll.
Nuget just follow your order.
 <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' ">
     <Package ...

When I use your lib in my .netcore 2.2 app => It download14 dlls more than possible, if you ship a version compatible .net standard 2.0, my app will have only one dll to download. :)

**Comment by bytefish** [comment]
Do you think continue supporting 1.3 makes a lot of sense? I have the feeling, that 97% of the world are using or going to use netstandard 2.0 anyway.

**Comment by jgiacomini** [comment]
Yes it's cost nothing to you, it s just one target :)

**Comment by bytefish** [comment]
On the other hand, maybe existing code uses it, so this change would qualify as a breaking change. And I don't want to increase to 3.0 right now.

**Comment by jgiacomini** [comment]
On one of my projet  I have supported lot of .netstandard versions you can read how I do it :
https://github.com/jgiacomini/Tiny.RestClient/blob/master/Tiny.RestClient/Tiny.RestClient.csproj

More the .netstandard is lower more I have to add dependencies hahaha. :)

**Comment by bytefish** [comment]
Cool Project! For every Xamarin.Forms and .NET project I introduce my own REST Client abstraction (based on the FcmSharp code). I might switch & contribute to yours instead.

My approach is different though. Basically I have introduced a Request Builder:

* https://github.com/bytefish/FcmSharp/blob/master/FcmSharp/FcmSharp/Http/Builder/HttpRequestMessageBuilder.cs

This ``HttpRequestBuilder`` enabled you to configure the Request (Headers, Methods, URL Segments, Query Parameters, JSON Content, ...). In the Clients I am then passing the HttpRequestBuilder around, so they can add some more Headers, like here:

https://github.com/bytefish/FcmSharp/blob/master/FcmSharp/FcmSharp/Http/Client/FcmHttpClient.cs#L69

I am not argueing for or against your design. But maybe this gives you an idea about different design choices and you might find it useful in other projects. :-)

**Pull request merged**
