### PR TITLE
Add Data to Mapping errors to simplify debugging / add line numbers on separate method / Various fixes/changes

### PR DESCRIPTION
**Pull request by ChrisMcKee**
_Firstly; this doesn't (or shouldn't) break existing functionality._ 
_I'm trying to get a feel for if there's any interest in developing this further; if there isn't I'll keep it in my own fork._

I required line numbers so I've overloaded the appropriate sections (tokenizers/mappers/error class) and added an option which is used to hit a branch within the CsvParser class. 

```
      CsvParserOptions csvParserOptions = new CsvParserOptions(true, null, new QuotedStringTokenizer(','), 8, true);
      csvParserOptions.StoreRowNumbers = true;
```

The enhancement to the mapping error results in the following:
image
Which makes it easier to work out the actual data (without including the row data in the error) and which parser was loaded.

I've completed the migration, removing properties (all this is csproj settable now, no more assembly.cs for assembly versions), and the ref'd libs which are part of core. 
Same for the tests, migrated over fully and target set to net45, which is fine to run the tests, fixes the VS integrations and removes issues around nunit fighting a huge backlog of issues. 
Tests all pass.

### CODE REVIEW

**Comment by bytefish** [comment]
Hi Chris,

Thanks for your efforts. They are really appreciated. 

This is a large commit and it will take time to review it, please do not expect any quick feedback.

**Comment by ChrisMcKee** [comment]
@bytefish the majority is style changes and migration fixes; the enhancements relatively contained. So if you decide it's not functionality you'd like to cover, it's worth considering the rest without the new functionality.

Ta

**Comment by bytefish** [comment]
@ChrisMcKee I have added a test, that shows how to keep track of the original row number in the file, without changing the base classes.

The idea is to have define three classes ``Row``, ``TokenizedRow`` and ``ParsedRow``. All hold the CSV row data and the original position in the file. Then we can implement a Parser, which works the same like the ``CsvParser`` coming with the framework.

```csharp
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TinyCsvParser.Mapping;

namespace TinyCsvParser.Test.Integration
{
    // Holds the Row Data and Line Number:
    public class Row
    {
        public readonly int Position;
        public readonly string Data;

        public Row(int position, string data)
        {
            Position = position;
            Data = data;
        }
    }

    // Holds the Tokenized Row Data and Line Number:
    public class TokenizedRow
    {
        public readonly int Position;
        public readonly string[] Data;

        public TokenizedRow(int position, string[] data)
        {
            Position = position;
            Data = data;
        }
    }

    // Holds the Parse Result and Line Number:
    public class ParsedRow<TEntity>
        where TEntity : class, new()
    {
        public readonly int Position;
        public readonly CsvMappingResult<TEntity> Result;

        public ParsedRow(int position, CsvMappingResult<TEntity> result)
        {
            Position = position;
            Result = result;
        }
    }

    // Implements a CsvParser, which counts rows:
    public class LineCountingCsvParser<TEntity>
        where TEntity : class, new()
    {
        private readonly CsvParserOptions options;
        private readonly CsvMapping<TEntity> mapping;

        public LineCountingCsvParser(CsvParserOptions options, CsvMapping<TEntity> mapping)
        {
            this.options = options;
            this.mapping = mapping;
        }

        public ParallelQuery<ParsedRow<TEntity>> Parse(IEnumerable<string> csvData)
        {
            if (csvData == null)
            {
                throw new ArgumentNullException("csvData");
            }

            var query = csvData
                .Select((x, pos) => new Row(pos, x))
                .Skip(options.SkipHeader ? 1 : 0)
                .AsParallel();

            // If you want to get the same order as in the CSV file, this option needs to be set:
            if (options.KeepOrder)
            {
                query = query.AsOrdered();
            }

            query = query
                .WithDegreeOfParallelism(options.DegreeOfParallelism)
                .Where(row => !string.IsNullOrWhiteSpace(row.Data));

            // Ignore Lines, that start with a comment character:
            if (!string.IsNullOrWhiteSpace(options.CommentCharacter))
            {
                query = query.Where(row => !row.Data.StartsWith(options.CommentCharacter));
            }

            return query
                .Select(row => new TokenizedRow(row.Position, options.Tokenizer.Tokenize(row.Data)))
                .Select(tokenizedRow => new ParsedRow<TEntity>(tokenizedRow.Position, mapping.Map(tokenizedRow.Data)));
        }

        public ParallelQuery<ParsedRow<TEntity>> ReadFromString(CsvReaderOptions csvReaderOptions, string csvData)
        {
            var lines = csvData.Split(csvReaderOptions.NewLine, StringSplitOptions.None);

            return Parse(lines);
        }

        public override string ToString()
        {
            return string.Format("CsvParser (Options = {0}, Mapping = {1})", options, mapping);
        }
    }

    [TestFixture]
    public class LineNumberCsvParserTest
    {
        private class Person
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public DateTime BirthDate { get; set; }
        }

        private class CsvPersonMapping : CsvMapping<Person>
        {
            public CsvPersonMapping()
            {
                MapProperty(0, x => x.FirstName);
                MapProperty(1, x => x.LastName);
                MapProperty(2, x => x.BirthDate);
            }
        }

        [Test]
        public void CsvParserWithLineCountingTest()
        {
            var csvParserOptions = new CsvParserOptions(true, new[] { ';' });
            var csvReaderOptions = new CsvReaderOptions(new[] { Environment.NewLine });
            var csvMapper = new CsvPersonMapping();
            var csvParser = new LineCountingCsvParser<Person>(csvParserOptions, csvMapper);

            var stringBuilder = new StringBuilder()
                .AppendLine("FirstName;LastName;BirthDate")
                .AppendLine("Philipp;Wagner;1986/05/12")
                .AppendLine("")
                .AppendLine("Max;Mustermann;2014/01/01");

            var result = csvParser
                .ReadFromString(csvReaderOptions, stringBuilder.ToString())
                .ToList();

            Assert.AreEqual(2, result.Count);

            Assert.AreEqual(1, result[0].Position);
            Assert.AreEqual(3, result[1].Position);

            // Asserts ...
        }
    }
}
```

**Comment by ChrisMcKee** [comment]
Neat; I only proposed it as an edit to the existing parser to reduce the footprint of the change; the use of keyvalue was to keep the heap size down, functionally its very similar which is nice. 
If you want the other changes that complete the conversion and fix the test project for vs2017 etal I can pull out the line number change from the PR?

**Comment by ChrisMcKee** [comment]
I'll update in a bit; thought I looks functionally similar, I'm not 100% it meets the same aim 👍

**Comment by ChrisMcKee** [comment]
Fhi. I reverted out my change to the parser. The remaining changes are around test compatibility, the example custom parser, csproj and Vs test compatibility

**Comment by ChrisMcKee** [comment]
I'm guessing there's no interest in pulling the remaining changes so i'll close this issue.

**Comment by bytefish** [comment]
It's not like there is no interest, but there was simply no time left for open source development in the last year. Anyway I have now added line numbers to the library and made some other breaking changes. The solution is more or less like the one we discussed here.

Thanks for your valuable feedback!

I have also migrated the projects to the recent Visual Studio 2017 Format, as you suggested.

I have also enhanced the error reporting. Although I am not particular happy with the error handling part, because I think it may still lack some important details on why a conversion fails. Still thinking about this one.

**Pull request closed without merging**
