### PR TITLE
Skip footer

### PR DESCRIPTION
**Pull request by amittleider**
Skip footers or extraneous lines at the end.

I can't commit it like this. Does anyone know how I can get this to still work with other version of dot net? SkipLast was added in netstandard 2.1.

### CODE REVIEW

**Comment by bytefish** [comment]
@amittleider Good job! I didn't know about SkipLast until you made the Pull Request. 😳 I will take a look into it and come back. 👍

**Comment by amittleider** [comment]
Thanks @bytefish .

One solution would be a preprocessing directive (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if) 

What do you think about that?

**Comment by bytefish** [comment]
Well, I would like to keep the API surface the same for all platforms. What I will try is to come up with an API, so you can configure the LINQ pipeline from the outside. This way you can configure ``SkipLast(...)`` for example when constructing the parser.

But I will need to fiddle around a bit to see, what's the best approach.

**Comment by bytefish** [comment]
I know this isn't the most straightforward way, but I would create an Extension method in your application code, that uses ``SkipLast``. This would require no change to the library. What do you think?

You could also take a look at the Unit Test referenced in this Pull Request.

```csharp
public static class MyCsvParserExtensions
{
    public static ParallelQuery<CsvMappingResult<TEntity>> ReadFromFile<TEntity>(this CsvParser<TEntity> csvParser, string fileName, Encoding encoding, int skipLast)
    {
        if (fileName == null)
        {
            throw new ArgumentNullException(nameof(fileName));
        }

        var lines = File
            .ReadLines(fileName, encoding)
            .SkipLast(skipLast)
            .Select((line, index) => new Row(index, line));

        return csvParser.Parse(lines);
    }
}
```

**Comment by amittleider** [comment]
Hey @bytefish ,

Thanks for the suggestion, it works perfectly!

Here's an example that reads from a string too:

```C#
using System;
using System.Linq;
using System.Text;
using TinyCsvParser;
using TinyCsvParser.Mapping;
using TinyCsvParser.Model;

namespace FinraClient
{
    public static class CsvParserExtensions
    {
        public static ParallelQuery<CsvMappingResult<TEntity>> ReadFromFinraString<TEntity>(this CsvParser<TEntity> csvParser, CsvReaderOptions csvReaderOptions, string csvData, Encoding encoding, int skipLast)
        {
            var lines = csvData
                .Split(csvReaderOptions.NewLine, StringSplitOptions.None)
                .SkipLast(2)
                .Select((line, index) => new Row(index, line));
            
            return csvParser.Parse(lines);
        }
    }
}
```

**Comment by bytefish** [comment]
Cool! I will add it to the README and Docs.

**Pull request closed without merging**
